### PR TITLE
Multiple routes

### LINKED ISSUE #15: Offer a shortlink
* some short link `pollistics.com/sfdqsdf`
* descriptive link à la gfycat `pollistics.com/watching-dragon-meme`
* something else

### PR DESCRIPTION
**Pull request by elsmr**
/{id} and /poll/{id} both work now

fixes #15 (for now)

### CODE REVIEW

**Review by Haroenv — CHANGES_REQUESTED** [review]
Good, but test needs to be changed to expect `/test123` instead of `/polls/test123`

**Review by Haroenv — APPROVED** [review]

**Comment by Haroenv** [comment]
Hah, my hotfix was remove the test (it had no coverage anyway iirc)

**Comment by elsmr** [comment]
ah, i'll remove that controller method then

**Comment by Haroenv** [comment]
But `/polls/whatever` should be 404 too if there's no such id, now it's showing the template empty

**Comment by Haroenv** [comment]
Anyway, LGTM for now

**Comment by elsmr** [comment]
I'll try to fix it later. You could create an issue for it.

**Comment by Haroenv** [comment]
The issue is #20

**Comment by elsmr** [comment]
:+1:

**Pull request merged**
