### PR TITLE
Visual

### PR DESCRIPTION
**Pull request by Maliek**
Make the poll visual in a pie diagram using d3pie.js

### CODE REVIEW

**Comment by Haroenv** [comment]
I'll introduce rollup, which should fix the codacy issues

**Review by elsmr — DISMISSED** [review]
good :hankey:, update readme with instuctions please

**Comment by Haroenv** [comment]
Yep, and also need to make it work xddddd @eliasmeire (I'm almost there)

**Comment by Maliek** [comment]
Good luck my friend!

**Comment by Haroenv** [comment]
@eliasmeire README changed, switched to rollup only for local files, get d3 and d3pie from node modules and other things should be es6 import/exported into main.js. Also should check if `options` is correct, since it's not going to run on every page (worries for later xd)

**Review by Maliek — COMMENTED** [review]
Look just good

**Review by hannnegoossens — APPROVED** [review]
Dikke pluim. Doe zo voort!

**Pull request merged**
